COMPONENT=TestC

CFLAGS += -I$(OSIAN_ROOT)/tinyos/tos/lib/onewire
CFLAGS += -I$(OSIAN_ROOT)/tinyos/tos/lib/onewire/interfaces
CFLAGS += -I$(OSIAN_ROOT)/tinyos/tos/chips/ds1825

PFLAGS += -I$(TOSDIR)/lib/serialprintf
include $(MAKERULES)

