COMPONENT=TestAppC
CFLAGS += -DGLOBAL_ADDR_LENGTH=1
CFLAGS += -I$(TOSROOT)/apps/breakfast/util/i2cPersistentStorage
CFLAGS += -I$(TOSROOT)/apps/breakfast/util/i2cRegister
CFLAGS += -I$(TOSROOT)/apps/breakfast/util/i2cDiscover
CFLAGS += -I$(TOSROOT)/apps/breakfast/util
CFLAGS += -I$(TOSROOT)/apps/breakfast/util/globalID
CFLAGS += -I$(TOSDIR)/chips/msp430/x2xxx/internalFlash

include $(MAKERULES)
