COMPONENT=TestAppC
CFLAGS+=-I$(TOSROOT)/apps/breakfast/util
CFLAGS+=-I$(TOSROOT)/apps/breakfast/util/globalID
CFLAGS+=-I$(TOSROOT)/apps/breakfast/util/i2cDiscover
CFLAGS+=-I$(TOSROOT)/apps/breakfast/util/i2cPersistentStorage
CFLAGS+=-I$(TOSROOT)/apps/breakfast/util/i2cRegister
CFLAGS+=-I$(TOSDIR)/lib/serialprintf

#TODO: argh, shouldn't be here
CFLAGS+=-I$(TOSDIR)/chips/msp430/x2xxx/internalFlash
include $(MAKERULES)
