COMPONENT=AnalogSensorBoardC
CFLAGS+=-I$(TOSDIR)/lib/serialprintf
CFLAGS+=-I$(TOSROOT)/apps/breakfast/util
CFLAGS+=-I$(TOSROOT)/apps/breakfast/util/globalID
CFLAGS+=-I$(TOSROOT)/apps/breakfast/util/i2cDiscover
#CFLAGS+=-I$(TOSROOT)/apps/breakfast/util/i2cRegister
CFLAGS+=-I$(TOSROOT)/apps/breakfast/util/i2cPersistentStorage
CFLAGS+=-I$(TOSROOT)/apps/breakfast/util/i2cCom

CFLAGS+=-I$(TOSROOT)/apps/breakfast/util/i2cTLVStorage
CFLAGS+=-I$(TOSROOT)/apps/breakfast/util/i2cSynch
CFLAGS+=-I$(TOSROOT)/apps/breakfast/util/i2cADCReader


include $(MAKERULES)
