COMPONENT=TestAppC
CFLAGS += -DGLOBAL_ADDR_LENGTH=1
CFLAGS += -I$(TOSROOT)/apps/breakfast/util/i2cRegister
CFLAGS += -I$(TOSROOT)/apps/breakfast/independent/echoRegister
CFLAGS += -I$(TOSROOT)/apps/breakfast/util/i2cDiscover
CFLAGS += -I$(TOSROOT)/apps/breakfast/util

include $(MAKERULES)
