COMPONENT=TestAppC
CFLAGS += -DI2C_GLOBAL_ADDR_LENGTH=4
CFLAGS += -I$(TOSROOT)/apps/breakfast/util/i2cDiscover
CFLAGS += -I$(TOSROOT)/apps/breakfast/util
CFLAGS += -DGLOBAL_ADDR_LSB=$(GLOBAL_ADDR_LSB)

include $(MAKERULES)
