#ifndef I2C_DISCOVERABLE_H
#define I2C_DISCOVERABLE_H

#define I2C_DISCOVERABLE_REGISTERS_SIZE GLOBAL_ADDR_LENGTH+1
#define I2C_DISCOVERY_ROUND_TIMEOUT 1024

#define I2C_INVALID_MASTER 0xffff
#define I2C_DISCOVERABLE_UNASSIGNED 0xfffe

#define I2C_DISCOVERABLE_REQUEST_ADDR 0xdc
#endif
