COMPONENT=TestReceiverAppC

PFLAGS += -I$(TOSDIR)/lib/serialprintf
PFLAGS += -I$(TOSDIR)/lib/rf1a-delayedSend
PFLAGS += -I$(TOSDIR)/lib/rf1a-multi/configs/includes
PFLAGS += -I$(TOSDIR)/lib/rf1a-multi/configs/generated

CFLAGS += -DSEND_1_OFFSET=1

#32mhz mclk
PFLAGS+=-DMSP430XV2_DCO_CONFIG=MSP430XV2_DCO_64MHz_RSEL7

include $(MAKERULES)
