/* Deviation = 19.042969 */
/* Base frequency = 901.999969 */
/* Carrier frequency = 903.999481 */
/* Channel number = 10 */
/* Carrier frequency = 903.999481 */
/* Modulated = true */
/* Modulation format = 2-GFSK */
/* Manchester enable = false */
/* Sync word qualifier mode = 30/32 sync word bits detected */
/* Preamble count = 4 */
/* Channel spacing = 199.951172 */
/* Carrier frequency = 903.999481 */
/* Data rate = 9.9926 */
/* RX filter BW = 101.562500 */
/* Data format = Normal mode */
/* Length config = Variable packet length mode. Packet length configured by the first byte after sync word */
/* CRC enable = true */
/* Packet length = 255 */
/* Device address = 0 */
/* Address config = No address check */
/* CRC autoflush = false */
/* PA ramping = false */
/* TX power = unknown */

/* PA table */
#define TINYOSRF1A_H_PA_TABLE {0xc0,0x00,0x00,0x00,0x00,0x00,0x00,0x00}


#define TINYOSRF1A_H_SMARTRF_SETTING_IOCFG2     0x2E
#define TINYOSRF1A_H_SMARTRF_SETTING_IOCFG1     0x2E
#define TINYOSRF1A_H_SMARTRF_SETTING_IOCFG0     0x29
#define TINYOSRF1A_H_SMARTRF_SETTING_FIFOTHR    0x47
#define TINYOSRF1A_H_SMARTRF_SETTING_SYNC1      0xD3
#define TINYOSRF1A_H_SMARTRF_SETTING_SYNC0      0x91
#define TINYOSRF1A_H_SMARTRF_SETTING_PKTLEN     0xFF
#define TINYOSRF1A_H_SMARTRF_SETTING_PKTCTRL1   0x04
#define TINYOSRF1A_H_SMARTRF_SETTING_PKTCTRL0   0x45
#define TINYOSRF1A_H_SMARTRF_SETTING_ADDR       0x00
#define TINYOSRF1A_H_SMARTRF_SETTING_CHANNR     0x0A
#define TINYOSRF1A_H_SMARTRF_SETTING_FSCTRL1    0x06
#define TINYOSRF1A_H_SMARTRF_SETTING_FSCTRL0    0x00
#define TINYOSRF1A_H_SMARTRF_SETTING_FREQ2      0x22
#define TINYOSRF1A_H_SMARTRF_SETTING_FREQ1      0xB1
#define TINYOSRF1A_H_SMARTRF_SETTING_FREQ0      0x3B
#define TINYOSRF1A_H_SMARTRF_SETTING_MDMCFG4    0xC8
#define TINYOSRF1A_H_SMARTRF_SETTING_MDMCFG3    0x93
#define TINYOSRF1A_H_SMARTRF_SETTING_MDMCFG2    0x13
#define TINYOSRF1A_H_SMARTRF_SETTING_MDMCFG1    0x22
#define TINYOSRF1A_H_SMARTRF_SETTING_MDMCFG0    0xF8
#define TINYOSRF1A_H_SMARTRF_SETTING_DEVIATN    0x34
#define TINYOSRF1A_H_SMARTRF_SETTING_MCSM2      0x07
#define TINYOSRF1A_H_SMARTRF_SETTING_MCSM1      0x3F
#define TINYOSRF1A_H_SMARTRF_SETTING_MCSM0      0x10
#define TINYOSRF1A_H_SMARTRF_SETTING_FOCCFG     0x16
#define TINYOSRF1A_H_SMARTRF_SETTING_BSCFG      0x6C
#define TINYOSRF1A_H_SMARTRF_SETTING_AGCCTRL2   0x03
#define TINYOSRF1A_H_SMARTRF_SETTING_AGCCTRL1   0x40
#define TINYOSRF1A_H_SMARTRF_SETTING_AGCCTRL0   0x91
#define TINYOSRF1A_H_SMARTRF_SETTING_WOREVT1    0x80
#define TINYOSRF1A_H_SMARTRF_SETTING_WOREVT0    0x00
#define TINYOSRF1A_H_SMARTRF_SETTING_WORCTRL    0xF0
#define TINYOSRF1A_H_SMARTRF_SETTING_FREND1     0x56
#define TINYOSRF1A_H_SMARTRF_SETTING_FREND0     0x10
#define TINYOSRF1A_H_SMARTRF_SETTING_FSCAL3     0xE9
#define TINYOSRF1A_H_SMARTRF_SETTING_FSCAL2     0x2A
#define TINYOSRF1A_H_SMARTRF_SETTING_FSCAL1     0x00
#define TINYOSRF1A_H_SMARTRF_SETTING_FSCAL0     0x1F
#define TINYOSRF1A_H_SMARTRF_SETTING_FSTEST     0x59
#define TINYOSRF1A_H_SMARTRF_SETTING_PTEST      0x7F
#define TINYOSRF1A_H_SMARTRF_SETTING_AGCTEST    0x3F
#define TINYOSRF1A_H_SMARTRF_SETTING_TEST2      0x81
#define TINYOSRF1A_H_SMARTRF_SETTING_TEST1      0x35
#define TINYOSRF1A_H_SMARTRF_SETTING_TEST0      0x09

#define TINYOSRF1A_H_GLOBAL_ID 28
